language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
    # Pull dependencies from GitHub
    - cd ..
    - git clone --depth=1 --branch=master git://github.com/textX/Arpeggio.git
    - pip install -e Arpeggio
    - git clone --depth=1 --branch=master git://github.com/textX/textX.git
    - pip install -e textX
    - cd textx-bibtex

install:
    - ./install-test.sh

script:
    - ./runtests.sh

after_success:
    - coveralls